# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6f4ee2de0a856a9cc213f8021ed0ef8f2033b814137c52388b19036b9a54c98ae485c749786cbe6369b9a31c82fb66edef34f44df805dad0a788e014a24e36c

test:
  secret_key_base: bee6d532a964a3148263c86ea9c6c4060c24f50b27f235cc257ec23446d8a3b7ad75e3d242027bd853684029ad9cfa9a8fc4d7d7242b6f608252a73cc435c367

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
